---
title: "Introducción"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Qué sí y qué no incluye este tutorial

Es muy común trabajar con datos espaciales (datos asociados a una latitud y longitud, sobre la superficie o a veces en un nivel en la atmósfera o determinada profundidad en el océano) organizados en arrays u poligonos. En este tutorial les proponemos trabajar con datos grillados organizados en tablas. Estas tablas podrían ser data.frames, tibbles o data.tables según la sintaxis y librerías de R que uses normalmente. 

Por supuesto ambos enfoques tienen sus pros y sus contras y dependerá de la tarea que se quiere realizar y los datos disponibles en el momento. Para tener en cuenta:

| | Arrays / Polígonos | Tablas |
|:---:|:------|:------|
|Pros | * Uso eficiente de la memoria</br> * Enfoque muy difundido</br> * Hay muchas herramientas disponibles  | * Permite trabajar los datos como cualquier otros aprovechando librerías conocidas |
|Cons | * Es necesario aprender a usar herramientas específicas  | * Los data.frames puede ocupan mucha memoria </br> * Algunos cálculos puede tomar mucho tiempo, es necesario optimizarlos |

Sí algún día se te ocurre leer un data.frame con varios millones de filas, es posible que {dplyr} no funcione muy bien, uno de los problemas es que esta librería hace copias de los objetos y si estos ocupan mucha memoría puede ser un problema. Una posible solución es usar la librería {data.table}, que tiene una sitaxis distinta o {dtplyr} que mantiene la sitaxis de {dplyr} con las ventajas de {data.table}. Pero no te preocupes, los datos que usaremos en el tutorial son aptos para cualquier computadora. 

### ¿Porqué usar datos tidy?


