---
title: "Untitled"
author: "Elio Campitelli"
date: "07/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(metR)

archivo <- system.file("extdata", "temperature.nc", package = "metR")


GlanceNetCDF(archivo)
```

```{r}
17*73*144*1
```

```{r}
ReadNetCDF(archivo)
```


```{r}
request <- list(
  format = "netcdf",
  product_type = "monthly_averaged_reanalysis",
  variable = c("mean_sea_level_pressure", "sea_surface_temperature", "total_precipitation"),
  year = c("1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020"),
  month = c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"),
  time = "00:00",
  dataset_short_name = "reanalysis-era5-single-levels-monthly-means",
  grid = "2.5/2.5",
  target = "temperatura_mar.nc"
)
```

```{r}
archivo <- ecmwfr::wf_request(request, path = "datos")
```

```{r}
GlanceNetCDF(archivo)
```

```{r}
datos <- ReadNetCDF(archivo, vars = "sst")
```

```{r}
library(dplyr)
library(ggplot2)
```


```{r}
datos %>% 
  filter(time == time[1]) %>% 
  ggplot(aes(longitude, latitude)) +
  geom_raster(aes(fill = sst))

```

```{r}
ReadNetCDF(archivo, vars = "sst", 
           subset = list(latitude = c(-90, 0),
                         longitude = c(100, 200))) %>% 
  filter(time == time[1]) %>% 
  ggplot(aes(longitude, latitude)) +
  geom_raster(aes(fill = sst))
```

```{r}
sst1 <- datos[time == time[1]]
```


```{r}
sst1 %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour2(aes(z = sst))
```



```{r}
sst1 %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = sst))
```

```{r}
mapa <- geom_polygon(data = map_data("world2"), 
                     aes(long, lat, group = group), 
                     inherit.aes = FALSE, fill = "white")
```


```{r}
sst1 %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = sst)) +
  mapa
```
```{r}
sst1 %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = sst), na.fill = TRUE)
```

```{r}
sst1 %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = sst), na.fill = TRUE) +
  mapa
```


```{r}
head(surface)
```

```{r}
surface %>% 
  ggplot(aes(x, y)) +
  geom_point(aes(colour = height))
```

```{r}
surface %>% 
  ggplot(aes(x, y)) +
  geom_contour_fill(aes(z = height))
```

```{r}
proj_string <- "+proj=lcc +lat_1=-30.9659996032715 +lat_2=-30.9659996032715 +lat_0=-30.9660034179688 +lon_0=296.432998657227 +a=6370000 +b=6370000 +over"

ggplot(surface, aes(x, y)) +
  geom_contour_fill(aes(z = height), proj = proj_string)
```

```{r}
sst1 %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = sst)) +
  geom_contour_fill(data = surface, aes(x, y, z = height), 
                    proj = proj_string)
```

```{r}
sst1 %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = sst)) +
  ggnewscale::new_scale_fill() +
  geom_contour_fill(data = surface, aes(x, y, z = height), 
                    proj = proj_string)
```

```{r}
sst1 %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = sst, fill = ..level..), 
                    breaks = c(272, 275, 280, 295, 305)) +
  scale_fill_viridis_c(super = ScaleDiscretised)
```


```{r}
sst1 %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = sst)) +
  scale_fill_divergent(midpoint = 290)
```

```{r}
colorblindr::edit_colors(last_plot(), 
                         colfun = colorspace::desaturate) %>% 
  cowplot::plot_grid()
```


```{r}
sst1 %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = sst)) +
  geom_contour_tanaka(aes(z = sst)) +
  scale_fill_divergent(midpoint = 290)
```

```{r}
colorblindr::edit_colors(last_plot(), 
                         colfun = colorspace::desaturate) %>% 
  cowplot::plot_grid()
```

```{r}
datos %>% 
  group_by(longitude, latitude, mes = data.table::month(time)) %>% 
  summarise(sst = mean(sst)) %>% 
  ungroup() %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = sst)) +
  facet_wrap(~mes)
```



```{r}
datos %>% 
  filter(latitude == 0 & longitude == 180) %>% 
  ggplot(aes(time, sst)) +
  geom_line()
```

```{r}
puntos <- tibble::tribble(~longitude, ~latitude,
                          180       , 0, 
                          170       , 50, 
                          280       , -60) 

ggplot(puntos, aes(longitude, latitude)) +
  geom_point() +
  mapa
```


```{r}
datos %>% 
  right_join(puntos) %>% 
  ggplot(aes(time, sst)) +
  geom_line() +
  facet_wrap(~longitude + latitude)
```

```{r}
datos <- datos %>% 
  group_by(mes = data.table::month(time), longitude, latitude) %>% 
  mutate(sst_a = sst - mean(sst)) %>% 
  ungroup() %>% 
  select(-mes)
```

```{r}
datos %>% 
  filter(time == unique(time)[229]) %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = sst_a)) +
  scale_fill_divergent() +
  mapa
  
```



`EOF()` -> Empitical Orthogonal Function

```{r}
eofs <- datos %>% 
  filter(!is.na(sst_a)) %>% 
  mutate(sst_a = sst_a*sqrt(cos(latitude+pi/180))) %>% 
  EOF(sst_a ~ longitude + latitude  | time, data = ., n = 1:2)
```

```{r}
str(eofs)
```

```{r}
eofs$left %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = sst_a)) +
  facet_wrap(~PC) +
  scale_fill_divergent()
```


```{r}
enso <- datos %>% 
  filter(abs(latitude) < 5 & between(ConvertLongitude(longitude), -170, -120)) %>% 
  group_by(time) %>% 
  summarise(enso34 = mean(sst_a)) %>% 
  ungroup()
```


```{r}
enso %>% 
  ggplot(aes(time, enso34)) +
  geom_line()
  
```

```{r}
presion <- ReadNetCDF("datos/temperatura_mar.nc", vars = c("msl", "tp"))
```



```{r}
correlaciones <- presion %>% 
  right_join(enso, by = "time") %>% 
  group_by(longitude, latitude) %>% 
  summarise(msl = cor(msl, enso34), 
            tp  = cor(tp, enso34)) %>% 
  ungroup()
```

```{r}
correlaciones %>% 
  tidyr::pivot_longer(cols = c(msl, tp)) %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = value)) +
  scale_fill_divergent() + 
  geom_polygon(data = map_data("world2"), aes(long, lat, group = group), 
               fill = NA, colour = "black", inherit.aes = FALSE, size = 0.2) +
  facet_wrap(~name)
```

# Preguntas:

¿Cómo mostrar p-valores? 

Esto es con data.table. Con `cor.test()` se calcula el estimador y el p-valor.
Luego, el campo de p-valores se puede mostrar como contornos, o como puntos, o de otra manera. 

```{r}
library(data.table)
presion %>% 
  .[as.data.table(enso), on = "time"] %>% 
  .[, cor.test(msl, enso34)[c("estimate", "p.value")], 
    by = .(longitude, latitude)] %>% 
  .[, p.value := p.adjust(p.value, "fdr")] %>% 
  ggplot(aes(longitude, latitude)) +
  geom_contour_fill(aes(z = estimate)) +
  geom_contour2(aes(z = p.value), breaks = 0.05) +
  scale_fill_divergent() + 
  geom_polygon(data = map_data("world2"), aes(long, lat, group = group), 
               fill = NA, colour = "black", inherit.aes = FALSE, size = 0.2)
  
```

Con dplyr **creo** que algo así debería funcionar.

```{r}
presion %>% 
  right_join(enso, by = "time") %>% 
  group_by(longitude, latitude) %>% 
  summarise(tibble(cor.test(msl, enso34)[c("estimate", "p.value")])) %>% 
  ungroup()
```

